# Generated by Django 3.2.18 on 2023-05-31 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20230530_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
