# Generated by Django 3.2.18 on 2023-05-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='task',
            new_name='todo',
        ),
    ]
