# Generated by Django 3.2.18 on 2023-05-25 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_task_game_todo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
