# Generated by Django 3.2.18 on 2023-05-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='completed',
        ),
    ]
