# Generated by Django 3.2.18 on 2023-05-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user',
            new_name='users',
        ),
    ]
