# Generated by Django 3.2.18 on 2023-05-25 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_user_game_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='users',
            new_name='user',
        ),
    ]
