# Generated by Django 3.2.18 on 2023-05-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_users_game_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='user',
            new_name='users',
        ),
    ]
