# Generated by Django 3.2.18 on 2023-05-26 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_rename_user_game_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='todo',
        ),
    ]
