# Generated by Django 3.2.18 on 2023-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tasks',
        ),
        migrations.AddField(
            model_name='todo',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
